#Makefile for lab10
# jeremiah Locke. CSCI 112, lab10
# 4/25/12

lab10: lab10.o LinkedFunctions.o
	gcc -o lab10 lab10.o LinkedFunctions.o
lab10.o: lab10.c
	gcc -c lab10.c
LinkedFunctions.o: LinkedFunctions.c
	gcc -c LinkedFunctions.c
